blog/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from . import settings

urlpatterns = [
                  # 引用blog_articles里面的urls.py
                  url(r'', include('blog_articles.urls', namespace='blog')),
                  url(r'^admin/', include(admin.site.urls)),
                  url(r'^draceditor/', include('draceditor.urls')),
                  url(r'^board/', include('msb.urls', namespace='msb')),
                  url(r'^account/', include('myuser.urls', namespace='account')),
                  url(r'^haystacksearch/', include('haystack.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL,
                                                                                         document_root=settings.STATIC_ROOT)

blog_articles/urls.py
from django.conf.urls import url, handler404, handler500
from django.conf.urls.static import static
from django.conf import settings
from . import views, rss
from . import manage_views as manage

handler404 = 'manage.page_not_found'

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^aboutme$', views.aboutme, name='aboutme'),
    url(r'^categories$', views.showcategories, name='categories'),
    url(r'^categories/(?P<category_id>\d+)$',
        views.CategoryView.as_view(), name='category'),
    # 文章详情
    url(r'^article/(?P<article_id>\d+)$',
        views.detail, name='detail'),
    url(r'^tag/(?P<tag_id>\d+)$', views.Tagview.as_view(), name='tag'),
    url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$',
        views.archive, name='archive'),
    # 写评论
    url(r'^article/(?P<article_id>\d+)/comment/$',
        views.write_comments, name='comment'),
    # 删除评论
    url(r'^delete_comment/(?P<comment_id>\d+)/$',
        views.delete_comment, name='delete_comment'),
    # 回复评论
    url(r'^reply_comment/(?P<comment_id>\d+)/$',
        views.reply_comment, name='reply_comment'),
    # 修改评论
    url(r'^edit_comment/(?P<comment_id>\d+)/$',
        views.edit_comment, name='edit_comment'),
    url(r'^search/$', views.search_article, name='search'),
    # 下面是管理后台的
    url(r'^myarticles/', manage.myarticles, name='myarticles'),
    url(r'change_titlephoto/(?P<article_id>\d+)/$', manage.change_titlephoto, name='titlephoto'),
    url(r'^delete_article/(?P<article_id>\d+)/$', manage.delete_article, name='delete_article'),
    url(r'^article_comment/(?P<article_id>\d+)/$', manage.article_comment, name='article_comment'),
    url(r'^manage_comment/edit/(?P<comment_id>\d+)/$', manage.edit_comment, name='manage_c_edit'),
    url(r'^manage_comment/delete/(?P<comment_id>\d+)/$', manage.delete_comment, name='manage_c_del'),
    url(r'^new_article/$', manage.new_article, name='new_article'),
    url(r'^edit_article/(?P<article_id>\d+)$',
        manage.edit_article, name='edit_article'),
    url(r'^management/$', manage.management_index, name='management'),
    url(r'^category_list/$', manage.manage_category, name='category_list'),
    url(r'^tag_list/$', manage.manage_tags, name='tag_list'),
    url(r'^edit_category/(?P<category_id>\d+)', manage.edit_category, name='edit_category'),
    url(r'^edit_tag/(?P<tag_id>\d+)', manage.edit_tag, name='edit_tag'),
    url(r'^delete_category/(?P<category_id>\d+)', manage.delete_category, name='delete_category'),
    url(r'^delete_tag/(?P<tag_id>\d+)', manage.delete_tag, name='delete_tag'),
    # 友链
    url(r'^link_list/$', manage.friendlink, name='link_list'),
    url(r'^delete_link/(?P<friends_id>\d+)/$', manage.delete_friends, name='del_link'),
    # 修改关于博客
    url(r'^manage_aboutme/(?P<id>\d+)$', manage.edit_aboutme, name='edit_aboutme'),
    # rss
    url(r'^latest/feed/$', rss.LatestArticle(), name='rss'),
]

msb/urls.py
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings
from . import views

urlpatterns = [
                  url(r'^$', views.MessageBoard, name='board'),
                  url(r'^manage/$', views.msb_manage, name='manage'),
                  url(r'^delete/(?P<message_id>\d+)/$', views.msb_manage, name='delete'),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

myuser/urls.py
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings
from . import views

urlpatterns = [
                  url(r'^login/$', views.user_login, name='login'),
                  url(r'^logout/$', views.user_logout, name='logout'),
                  url(r'^register/$', views.user_register, name='register'),
                  url(r'^profile/(?P<user_id>\d+)$', views.profile, name='profile'),
                  url(r'^avatar/(?P<user_id>\d+)$', views.change_avatar, name='change_avatar'),
                  # 私信
                  url(r'^post_private/(?P<receiver_id>\d+)/$', views.send_messages, name='send_private'),
                  # 用户管理
                  url(r'^userlist/$', views.userlist, name='userlist'),
                  url(r'^disable/(?P<user_id>\d+)/$', views.disabled_user, name='disable'),
                  url(r'^able/(?P<user_id>\d+)/$', views.abled_user, name='able'),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blog_articles/forms.py
from .models import Article, Category, Tag, Comments, Friends, Aboutme
from myuser.models import allUser
from django import forms
from draceditor.fields import DraceditorFormField, DraceditorWidget


class ReplyForm(forms.ModelForm):
    """回复表单"""
    content = forms.CharField()

    class Meta:
        model = Comments
        fields = ['content']


class CommentForm(forms.ModelForm):
    """评论表单"""
    content = forms.CharField(
        widget=forms.Textarea(attrs={'class': 'color-form-control', 'id': 'commentcontent', 'rows': 3}))

    class Meta:
        model = Comments
        fields = ['content']


class ArticleForm(forms.ModelForm):
    """文章表单"""
    title = forms.CharField(max_length=70)
    author = forms.ModelChoiceField(queryset=allUser.objects.filter(is_superuser=True),
                                    widget=forms.Select(attrs={'data-am-selected': None}))
    category = forms.ModelChoiceField(queryset=Category.objects.all(),
                                      widget=forms.Select(attrs={'data-am-selected': None}))
    tag = forms.ModelMultipleChoiceField(queryset=Tag.objects.all(),
                                         widget=forms.SelectMultiple(
                                             attrs={'multiple': None, 'data-am-selected': "{btnWidth: '50%'}"}))
    abstract = forms.CharField(max_length=100)
    body = forms.CharField(widget=forms.Textarea)

    class Meta:
        model = Article
        fields = ['title', 'author', 'category', 'tag', 'abstract', 'body', 'status']


class TitlePhotoForm(forms.ModelForm):
    titlephoto = forms.ImageField()

    class Meta:
        model = Article
        fields = ['titlephoto']

class CategoryForm(forms.ModelForm):
    """分类表单"""
    name = forms.CharField(max_length=20,
                           widget=forms.TextInput(attrs={'class': 'am-form-field am-round', 'style': 'width:50%'}))

    class Meta:
        model = Category
        fields = ['name']
        labels = {'name': ''}


class TagForm(forms.ModelForm):
    """标签表单"""
    name = forms.CharField(max_length=20,
                           widget=forms.TextInput(attrs={'class': 'am-form-field am-round', 'style': 'width:50%'}))

    class Meta:
        model = Tag
        fields = '__all__'
        labels = {'name': ''}


class LinkForm(forms.ModelForm):
    name = forms.CharField(max_length=20,
                           label='名称',
                           widget=forms.TextInput(attrs={'class': 'am-form-field am-round', 'style': 'width:50%'}))
    links = forms.URLField(label='链接',
                           widget=forms.URLInput(attrs={'class': 'am-form-field am-round', 'style': 'width:50%'}))

    class Meta:
        model = Friends
        fields = ['name', 'links']
        labels = {'name': '名称', 'links': '链接'}


class AboutForm(forms.ModelForm):
    blog_name = forms.CharField(label='博客名称')
    admin_email = forms.EmailField(label='你的邮箱')
    other = forms.CharField(
        label='其他信息',
        widget=forms.Textarea(attrs={'rows': 3, 'cols': 80}))

    class Meta:
        model = Aboutme
        fields = ['blog_name', 'admin_email', 'other']

blog_articles/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect, Http404, HttpResponse
from django.db.models import Count
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from myuser.models import allUser
from .models import Article, Category, Aboutme, Tag, Comments, Friends
from .forms import CommentForm, ArticleForm, CategoryForm, TagForm, ReplyForm
from haystack.forms import SearchForm
from django.core.urlresolvers import reverse


class IndexView(ListView):
    """博客主页文章列表"""
    # template_name = "blog_articles/new/index.html"
    template_name = 'blog_articles/new/index.html'
    context_object_name = "article_list"

    # 返回文章,前5篇
    def get_queryset(self):
        article_list = Article.objects.filter(status='p').order_by('-create_time')[0:5]
        return article_list

    def get_context_data(self, **kwargs):
        # 增加额外的数据，这里返回一个文章分类，以字典的形式
        # 显示前五项最新修改的分类
        kwargs['category_list'] = Category.objects.order_by('-modified_time')[0:5]
        # 标签列表
        kwargs['tag_list'] = Tag.objects.all().order_by('name')
        kwargs['comment_list'] = Comments.objects.all().order_by('-published_time')[:5]
        return super(IndexView, self).get_context_data(**kwargs)


class ArticleDetailView(DetailView):
    """文章详情页视图"""
    model = Article

    template_name = "blog_articles/new/detail.html"

    context_object_name = "article"

    pk_url_kwarg = 'article_id'

    # get_object() 返回该视图要显示的对象
    def get_object(self):
        context = super(ArticleDetailView, self).get_object()
        return context

    def get_context_data(self, **kwargs):
        kwargs['category_list'] = Category.objects.all().order_by('name')
        kwargs['form'] = CommentForm()
        kwargs['comment_list'] = self.object.comments_set.all()
        return super(ArticleDetailView, self).get_context_data(**kwargs)


def detail(request, article_id):
    article = Article.objects.get(id=article_id)
    article.add_reading()
    category_list = Category.objects.all().order_by('name')
    form = CommentForm()
    replyform = ReplyForm()
    comment_list = article.comments_set.all()
    context = {'article': article,
               'category_list': category_list,
               'form': form,
               'replyform': replyform,
               'comment_list': comment_list}
    return render(request, 'blog_articles/new/detail.html', context)


class CategoryView(ListView):
    """单个分类下的文章列表视图--类形式"""

    template_name = "blog_articles/category.html"
    # 指定需要渲染的模板

    context_object_name = "article_list"

    # 指定模板中需要使用的上下文对象的名字

    def get_queryset(self):
        # get_queryset 的作用已在第一篇中有介绍，不再赘述
        article_list = Article.objects.filter(category=self.kwargs['category_id'], status='p')
        # 使用了分类的id作为关键字参数（category_id）传递给了CategoryView，传递的参数在kwargs属性中获取。
        return article_list

    # 给视图增加额外的数据
    def get_context_data(self, **kwargs):
        # 增加一个category_list,用于在页面显示所有分类，按照名字排序
        kwargs['category_list'] = Category.objects.all().order_by('name')
        # 获取正确的分类id，以便在标题栏正确显示分类名称
        kwargs['category'] = Category.objects.get(id=self.kwargs['category_id'])
        # 统计分类下的文章数量
        kwargs['count'] = Category.objects.annotate(num=Count('article'))
        return super(CategoryView, self).get_context_data(**kwargs)


class Tagview(ListView):
    template_name = 'blog_articles/tag.html'

    context_object_name = 'article_list'

    def get_queryset(self):
        article_list = Article.objects.filter(tag=self.kwargs['tag_id'], status='p')
        return article_list

    def get_context_data(self, **kwargs):
        kwargs['tag_list'] = Tag.objects.all().order_by('name')
        kwargs['tag'] = Tag.objects.get(id=self.kwargs['tag_id'])
        return super(Tagview, self).get_context_data(**kwargs)


# 单个分类下的文章列表视图-次选-函数形式
# def categoryview(request, category_id):
#     category = Category.objects.get(id=category_id)
#     article_list = category.article_set.order_by('-modified_time')
#     context = {'category': category, 'article_list': article_list}
#     return render(request, 'blog_articles/category.html', context)

def aboutme(request):
    """显示关于博客的页面"""

    # 只取第一条数据
    about = Aboutme.objects.all()[0]
    friend_link_list = Friends.objects.all()
    context = {'about': about, 'friend_link_list': friend_link_list, }
    return render(request, 'blog_articles/aboutme.html', context)


def showcategories(request):
    """分类主页面"""
    # 分类下没有文章不显示
    category_list = Category.objects.all()
    context = {'category_list': category_list}
    return render(request, 'blog_articles/new/categories.html', context)


def archive(request, year, month):
    """日期归档视图函数"""
    string = str(year) + '-' + str(month)
    article_list = Article.objects.filter(create_time__startswith=string)
    category_list = Category.objects.all().order_by('-modified_time')[0:5]
    tag_list = Tag.objects.all().order_by('name')
    context = {'article_list': article_list, 'category_list': category_list,
               'tag_list': tag_list}
    return render(request, 'blog_articles/new/index.html', context)


# @login_required
# def write_comments(request, article_id):
#     """评论"""
#     if request.method != 'POST':
#         form = CommentForm()
#
#     else:
#         form = CommentForm(request.POST)
#         if form.is_valid():
#             article = Article.objects.get(id=article_id)
#             user = request.user
#             comment = form.save(commit=False)
#             comment.article = article
#             comment.user = user
#             form.save()
#             # return redirect(to='article', id=article_id)
#             return redirect('blog:detail', article_id=article_id)
#
#     return redirect('blog:detail', article_id=article_id)

@login_required
def write_comments(request, article_id):
    """评论"""
    if request.method == 'POST':
        user = request.user
        content = request.POST['content']
        article = Article.objects.get(id=article_id)
        Comments.objects.create(user=user, content=content, article=article)
        print(user, content, article_id)
        return HttpResponse('发送成功')
    else:
        return HttpResponse('发送失败')


@login_required
def reply_comment(request, comment_id):
    """回复评论"""
    related = Comments.objects.get(id=comment_id)
    article = related.article
    article_id = article.id
    if request.method != "POST":
        form = ReplyForm()
    else:
        form = ReplyForm(data=request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            user = request.user
            comment.article = article
            comment.related = related
            comment.user = user
            form.save()
            realcomment = Comments.objects.filter(article=article).order_by('-published_time')[0]
            url = "/article/" + str(article.id) + "#commentboard" + str(realcomment.id)
            return HttpResponseRedirect(redirect_to=url)
            # return redirect(to='blog:detail', article_id=article_id)
    return HttpResponse('<script>history.back()</script>')


# @login_required
# def reply_comment(request, comment_id):
#     """回复评论"""
#     if request.method == "POST":
#         related = Comments.objects.get(id=comment_id)
#         article = related.article
#         user = request.user
#         content = request.POST['reply']
#         print(related, article, user, content)
#         # Comments.objects.create(user=user, article=article, content=content, related=related)
#         # return HttpResponse('ok')



@login_required
def edit_comment(request, comment_id):
    """修改评论"""
    comment = Comments.objects.get(id=comment_id)
    article_id = comment.article_id
    if request.method != "POST":
        form = CommentForm(instance=comment)
    else:
        form = CommentForm(instance=comment, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('blog:detail', article_id=article_id)
    context = {'comment_form': form, 'comment': comment, 'article': article_id}
    return render(request, 'blog_articles/edit_comment.html', context)


@login_required
def delete_comment(request, comment_id):
    """文章详情页删除评论"""
    comment = Comments.objects.get(id=comment_id)
    article_id = comment.article_id
    comment.delete()
    return redirect('blog:detail', article_id=article_id)


def search_article(request):
    """文章搜索"""
    keyword = request.GET['q']
    # haystack.SearchForm
    form = SearchForm(request.GET)
    articles = form.search()
    messages = '关键字 \'{}\' 搜索结果'.format(keyword)
    context = {
        'articles': articles,
        'messages': messages,
    }
    return render(request, 'blog_articles/article_search.html', context)


def edit_comment(request, comment_id):
    """文章详情页修改评论"""
    comment = Comments.objects.get(id=comment_id)
    article_id = comment.article_id
    if request.method != "POST":
        form = CommentForm(instance=comment)
    else:
        form = CommentForm(instance=comment, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('blog:detail', article_id=article_id)
    context = {'comment_form': form, 'comment': comment, 'article': article_id}
    return render(request, 'blog_articles/edit_comment.html', context)

blog_articles/templates/blog_articles/newmanage/index.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>后台管理</title>
    <link rel="stylesheet" href="/static/amaze-assets/css/amazeui.min.css"/>
    <link rel="stylesheet" href="/static/admin_assets/css/core.css"/>
    <link rel="stylesheet" href="/static/admin_assets/css/menu.css"/>
    <link rel="stylesheet" href="/static/admin_assets/css/index.css"/>
    <link rel="stylesheet" href="/static/admin_assets/css/admin.css"/>
    <link rel="stylesheet" href="/static/admin_assets/css/page/typography.css"/>
    <link rel="stylesheet" href="/static/admin_assets/css/page/form.css"/>
    <link rel="stylesheet" href="/static/admin_assets/css/component.css"/>
</head>
<body>
<!-- Begin page -->
<header class="am-topbar am-topbar-fixed-top">
    <div class="am-topbar-left am-hide-sm-only">
        <a href="{% url 'blog:management' %}" class=""><h1>后台管理</h1></a>
    </div>

    <div class="contain">
        <ul class="am-nav am-navbar-nav am-navbar-left">
            <li><h1 class="page-title">{% block title %}{% endblock %}</h1></li>
        </ul>
    </div>
</header>
<!-- end page -->


<div class="admin">
    <!-- sidebar start -->
    <div class="admin-sidebar am-offcanvas  am-padding-0" id="admin-offcanvas">
        <div class="am-offcanvas-bar admin-offcanvas-bar">
            <!-- User -->
            <div class="user-box am-hide-sm-only">
                <div class="user-img">
                    <img src="{{ user.avatar.url }}" alt="user-img"
                         class="img-circle img-thumbnail img-responsive">
                </div>
                <h5><a href="{% url 'account:profile' user.id %}">{{ user.username }}</a></h5>
            </div>
            <!-- End User -->

            <ul class="am-list admin-sidebar-list">
                <li>
                    <a href="{% url 'blog:index' %}"><span class="am-icon-home am-icon-sm">&nbsp;主页</span></a>
                </li>
                <li><a href="{% url 'blog:management' %}">后台导航</a></li>
                <li><a href="{% url 'blog:myarticles' %}">我的文章</a></li>
                <li><a href="{% url 'blog:tag_list' %}">简易标签管理</a></li>
                <li><a href="{% url 'blog:category_list' %}">简易分类管理</a></li>
                <li><a href="{% url 'blog:new_article' %}">撰写新文章</a></li>
                <li><a href="{% url 'account:userlist' %}">用户列表</a></li>
                <li><a href="{% url 'blog:link_list' %}">友链管理</a></li>
                <li><a href="{% url 'msb:manage' %}">留言管理</a></li>
                <li><a href="{% url 'blog:edit_aboutme' 1 %}">博客信息管理</a></li>
                <li>&nbsp;</li>
                <li>&nbsp;</li>
            </ul>
        </div>
    </div>
    <!-- sidebar end -->


    <!-- Start right Content here -->
    <div class="content-page">
        {% block content %}
        {% endblock %}
    </div>
    <!-- end right Content here -->
</div>
</div>

<!-- navbar -->
<a href="admin-offcanvas" class="am-icon-btn am-icon-th-list am-show-sm-only admin-menu"
   data-am-offcanvas="{target: '#admin-offcanvas'}"><!--<i class="fa fa-bars" aria-hidden="true"></i>--></a>

<script type="text/javascript" src="/static/admin_assets/js/jquery-2.1.0.js"></script>
<script type="text/javascript" src="/static/amaze-assets//js/amazeui.min.js"></script>
<script type="text/javascript" src="/static/admin_assets/js/app.js"></script>
<script type="text/javascript" src="/static/admin_assets/js/blockUI.js"></script>
<script type="text/javascript" src="/static/admin_assets/js/charts/echarts.min.js"></script>
<script type="text/javascript" src="/static/admin_assets/js/charts/indexChart.js"></script>

</body>

</html>

blog_articles/templates/blog_articles/newmanage/myarticles.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>后台管理</title>
    <link rel="stylesheet" href="/static/amaze-assets/css/amazeui.min.css"/>
    <link rel="stylesheet" href="/static/admin_assets/css/core.css"/>
    <link rel="stylesheet" href="/static/admin_assets/css/menu.css"/>
    <link rel="stylesheet" href="/static/admin_assets/css/index.css"/>
    <link rel="stylesheet" href="/static/admin_assets/css/admin.css"/>
    <link rel="stylesheet" href="/static/admin_assets/css/page/typography.css"/>
    <link rel="stylesheet" href="/static/admin_assets/css/page/form.css"/>
    <link rel="stylesheet" href="/static/admin_assets/css/component.css"/>
</head>
<body>
<!-- Begin page -->
<header class="am-topbar am-topbar-fixed-top">
    <div class="am-topbar-left am-hide-sm-only">
        <a href="index.html" class=""><h1>后台管理</h1></a>
    </div>

    <div class="contain">
    </div>
</header>
<!-- end page -->


<div class="admin">
    <!--<div class="am-g">-->
    <!-- ========== Left Sidebar Start ========== -->
    <!--<div class="left side-menu am-hide-sm-only am-u-md-1 am-padding-0">
        <div class="slimScrollDiv" style="position: relative; overflow: hidden; width: auto; height: 548px;">
            <div class="sidebar-inner slimscrollleft" style="overflow: hidden; width: auto; height: 548px;">-->
    <!-- sidebar start -->
    <div class="admin-sidebar am-offcanvas  am-padding-0" id="admin-offcanvas">
        <div class="am-offcanvas-bar admin-offcanvas-bar">
            <!-- User -->
            <div class="user-box am-hide-sm-only">
                <div class="user-img">
                    <img src="{{ user.avatar.url }}" alt="user-img"
                         class="img-circle img-thumbnail img-responsive">
                </div>
                <h5><a href="{% url 'account:profile' user.id %}">{{ user.username }}</a></h5>
            </div>
            <!-- End User -->

            <ul class="am-list admin-sidebar-list">
                <li>
                    <a href="{% url 'blog:index' %}"><span class="am-icon-home am-icon-sm">&nbsp;主页</span></a>
                </li>
                <li><a href="{% url 'blog:management' %}">后台导航</a></li>
                <li><a href="{% url 'blog:myarticles' %}">我的文章</a></li>
                <li><a href="{% url 'blog:tag_list' %}">简易标签管理</a></li>
                <li><a href="{% url 'blog:category_list' %}">简易分类管理</a></li>
                <li><a href="{% url 'blog:new_article' %}">撰写新文章</a></li>
                <li><a href="{% url 'account:userlist' %}">用户列表</a></li>
                <li><a href="{% url 'blog:link_list' %}">友链管理</a></li>
                <li><a href="{% url 'blog:edit_aboutme' 1 %}">博客信息管理</a></li>
            </ul>
            <br><br>
        </div>
    </div>
    <!-- sidebar end -->
    <!-- Start right Content here -->
    <div class="content-page">
        <!-- Start content -->
        <div class="card-box">
            <div class="content">
                <div class="am-g">

                    <div class=" am-u-lg-12 am-u-md-12" style="padding-top: 25px">
                        <p><b>文章列表</b>&nbsp;
                            <a href="{% url 'blog:new_article' %}" style="float: right">
                                <button class="am-btn am-round am-btn-warning">添加文章</button>
                            </a>
                        </p>

                        <table class="am-table am-table-hover">
                            <thead>
                            <tr>
                                <th class="table-title">标题</th>
                                <th class="table-author am-hide-sm-only">作者</th>
                                <th class="table-date am-hide-sm-only">发表日期</th>
                                <th class="table-detail">状态</th>
                                <th class="table-set">操作</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for article in article_list %}
                                <tr>
                                    <td><a href="{% url 'blog:detail' article.id %}">{{ article.title }}</a></td>
                                    <td class="am-hide-sm-only">{{ article.author }}</td>
                                    <td class="am-hide-sm-only">{{ article.create_time }}</td>
                                    <td>
                                        {% if article.status == 'p' %}
                                            发布
                                        {% else %}
                                            草稿
                                        {% endif %}
                                    </td>
                                    <td>
                                        <div class="am-btn-toolbar">
                                            <div class="am-btn-group am-btn-group-xs">
                                                <a href="{% url 'blog:article_comment' article.id %}">
                                                    <button class="am-btn am-btn-default am-btn-xs"><span
                                                            class="am-icon-pencil-square-o"></span> 评论管理
                                                    </button>
                                                </a>
                                                <button class="am-btn am-btn-success am-btn-xs"
                                                        data-am-collapse="{target:'#dialog{{ article.id }}'}"><span
                                                        class="am-icon-photo"></span> 题图
                                                </button>
                                                <a href="{% url 'blog:edit_article' article.id %}">
                                                    <button class="am-btn am-btn-primary am-btn-xs"><span
                                                            class="am-icon-copy"></span> 编辑
                                                    </button>
                                                </a>
                                                <a href="{% url 'blog:delete_article' article.id %}">
                                                    <button class="am-btn am-btn-danger am-btn-xs">
                                                        <span class="am-icon-trash-o"></span> 删除
                                                    </button>
                                                </a>
                                            </div>
                                        </div>

                                        <div id="dialog{{ article.id }}"
                                             class="am-collapse"
                                             style="padding-top: 5px">
                                            <p>当前题图：</p>
                                            <img src="{{ article.titlephoto.url }}" width="160" height="90">
                                            <p>更换题图：</p>
                                            <form action="{% url 'blog:titlephoto' article.id %}" method="post"
                                                  enctype="multipart/form-data">
                                                {% csrf_token %}
                                                {{ form.titlephoto }}
                                                <button type="submit" class="am-btn am-round am-btn-default">更换图片
                                                </button>
                                            </form>
                                        </div>

                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- end right Content here -->
    <!--</div>-->
</div>

<!-- navbar -->
<a href="admin-offcanvas" class="am-icon-btn am-icon-th-list am-show-sm-only admin-menu"
   data-am-offcanvas="{target: '#admin-offcanvas'}"><!--<i class="fa fa-bars" aria-hidden="true"></i>--></a>

<script type="text/javascript" src="/static/admin_assets/js/jquery-2.1.0.js"></script>
<script type="text/javascript" src="/static/amaze-assets//js/amazeui.min.js"></script>
<script type="text/javascript" src="/static/admin_assets/js/app.js"></script>
<script type="text/javascript" src="/static/admin_assets/js/blockUI.js"></script>
<script type="text/javascript" src="/static/admin_assets/js/charts/echarts.min.js"></script>
<script type="text/javascript" src="/static/admin_assets/js/charts/indexChart.js"></script>

</body>

</html>