blog/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from . import settings

urlpatterns = [
                  # 引用blog_articles里面的urls.py
                  url(r'', include('blog_articles.urls', namespace='blog')),
                  url(r'^admin/', include(admin.site.urls)),
                  url(r'^draceditor/', include('draceditor.urls')),
                  url(r'^board/', include('msb.urls', namespace='msb')),
                  url(r'^account/', include('myuser.urls', namespace='account')),
                  url(r'^haystacksearch/', include('haystack.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL,
                                                                                         document_root=settings.STATIC_ROOT)

blog_articles/urls.py
from django.conf.urls import url, handler404, handler500
from django.conf.urls.static import static
from django.conf import settings
from . import views, rss
from . import manage_views as manage

handler404 = 'manage.page_not_found'

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^aboutme$', views.aboutme, name='aboutme'),
    url(r'^categories$', views.showcategories, name='categories'),
    url(r'^categories/(?P<category_id>\d+)$',
        views.CategoryView.as_view(), name='category'),
    # 文章详情
    url(r'^article/(?P<article_id>\d+)$',
        views.detail, name='detail'),
    url(r'^tag/(?P<tag_id>\d+)$', views.Tagview.as_view(), name='tag'),
    url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$',
        views.archive, name='archive'),
    # 写评论
    url(r'^article/(?P<article_id>\d+)/comment/$',
        views.write_comments, name='comment'),
    # 删除评论
    url(r'^delete_comment/(?P<comment_id>\d+)/$',
        views.delete_comment, name='delete_comment'),
    # 回复评论
    url(r'^reply_comment/(?P<comment_id>\d+)/$',
        views.reply_comment, name='reply_comment'),
    # 修改评论
    url(r'^edit_comment/(?P<comment_id>\d+)/$',
        views.edit_comment, name='edit_comment'),
    url(r'^search/$', views.search_article, name='search'),
    # 下面是管理后台的
    url(r'^myarticles/', manage.myarticles, name='myarticles'),
    url(r'change_titlephoto/(?P<article_id>\d+)/$', manage.change_titlephoto, name='titlephoto'),
    url(r'^delete_article/(?P<article_id>\d+)/$', manage.delete_article, name='delete_article'),
    url(r'^article_comment/(?P<article_id>\d+)/$', manage.article_comment, name='article_comment'),
    url(r'^manage_comment/edit/(?P<comment_id>\d+)/$', manage.edit_comment, name='manage_c_edit'),
    url(r'^manage_comment/delete/(?P<comment_id>\d+)/$', manage.delete_comment, name='manage_c_del'),
    url(r'^new_article/$', manage.new_article, name='new_article'),
    url(r'^edit_article/(?P<article_id>\d+)$',
        manage.edit_article, name='edit_article'),
    url(r'^management/$', manage.management_index, name='management'),
    url(r'^category_list/$', manage.manage_category, name='category_list'),
    url(r'^tag_list/$', manage.manage_tags, name='tag_list'),
    url(r'^edit_category/(?P<category_id>\d+)', manage.edit_category, name='edit_category'),
    url(r'^edit_tag/(?P<tag_id>\d+)', manage.edit_tag, name='edit_tag'),
    url(r'^delete_category/(?P<category_id>\d+)', manage.delete_category, name='delete_category'),
    url(r'^delete_tag/(?P<tag_id>\d+)', manage.delete_tag, name='delete_tag'),
    # 友链
    url(r'^link_list/$', manage.friendlink, name='link_list'),
    url(r'^delete_link/(?P<friends_id>\d+)/$', manage.delete_friends, name='del_link'),
    # 修改关于博客
    url(r'^manage_aboutme/(?P<id>\d+)$', manage.edit_aboutme, name='edit_aboutme'),
    # rss
    url(r'^latest/feed/$', rss.LatestArticle(), name='rss'),
]

msb/urls.py
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings
from . import views

urlpatterns = [
                  url(r'^$', views.MessageBoard, name='board'),
                  url(r'^manage/$', views.msb_manage, name='manage'),
                  url(r'^delete/(?P<message_id>\d+)/$', views.msb_manage, name='delete'),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

myuser/urls.py
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings
from . import views

urlpatterns = [
                  url(r'^login/$', views.user_login, name='login'),
                  url(r'^logout/$', views.user_logout, name='logout'),
                  url(r'^register/$', views.user_register, name='register'),
                  url(r'^profile/(?P<user_id>\d+)$', views.profile, name='profile'),
                  url(r'^avatar/(?P<user_id>\d+)$', views.change_avatar, name='change_avatar'),
                  # 私信
                  url(r'^post_private/(?P<receiver_id>\d+)/$', views.send_messages, name='send_private'),
                  # 用户管理
                  url(r'^userlist/$', views.userlist, name='userlist'),
                  url(r'^disable/(?P<user_id>\d+)/$', views.disabled_user, name='disable'),
                  url(r'^able/(?P<user_id>\d+)/$', views.abled_user, name='able'),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blog_articles/forms.py
from .models import Article, Category, Tag, Comments, Friends, Aboutme
from myuser.models import allUser
from django import forms
from draceditor.fields import DraceditorFormField, DraceditorWidget


class ReplyForm(forms.ModelForm):
    """回复表单"""
    content = forms.CharField()

    class Meta:
        model = Comments
        fields = ['content']


class CommentForm(forms.ModelForm):
    """评论表单"""
    content = forms.CharField(
        widget=forms.Textarea(attrs={'class': 'color-form-control', 'id': 'commentcontent', 'rows': 3}))

    class Meta:
        model = Comments
        fields = ['content']


class ArticleForm(forms.ModelForm):
    """文章表单"""
    title = forms.CharField(max_length=70)
    author = forms.ModelChoiceField(queryset=allUser.objects.filter(is_superuser=True),
                                    widget=forms.Select(attrs={'data-am-selected': None}))
    category = forms.ModelChoiceField(queryset=Category.objects.all(),
                                      widget=forms.Select(attrs={'data-am-selected': None}))
    tag = forms.ModelMultipleChoiceField(queryset=Tag.objects.all(),
                                         widget=forms.SelectMultiple(
                                             attrs={'multiple': None, 'data-am-selected': "{btnWidth: '50%'}"}))
    abstract = forms.CharField(max_length=100)
    body = forms.CharField(widget=forms.Textarea)

    class Meta:
        model = Article
        fields = ['title', 'author', 'category', 'tag', 'abstract', 'body', 'status']


class TitlePhotoForm(forms.ModelForm):
    titlephoto = forms.ImageField()

    class Meta:
        model = Article
        fields = ['titlephoto']

class CategoryForm(forms.ModelForm):
    """分类表单"""
    name = forms.CharField(max_length=20,
                           widget=forms.TextInput(attrs={'class': 'am-form-field am-round', 'style': 'width:50%'}))

    class Meta:
        model = Category
        fields = ['name']
        labels = {'name': ''}


class TagForm(forms.ModelForm):
    """标签表单"""
    name = forms.CharField(max_length=20,
                           widget=forms.TextInput(attrs={'class': 'am-form-field am-round', 'style': 'width:50%'}))

    class Meta:
        model = Tag
        fields = '__all__'
        labels = {'name': ''}


class LinkForm(forms.ModelForm):
    name = forms.CharField(max_length=20,
                           label='名称',
                           widget=forms.TextInput(attrs={'class': 'am-form-field am-round', 'style': 'width:50%'}))
    links = forms.URLField(label='链接',
                           widget=forms.URLInput(attrs={'class': 'am-form-field am-round', 'style': 'width:50%'}))

    class Meta:
        model = Friends
        fields = ['name', 'links']
        labels = {'name': '名称', 'links': '链接'}


class AboutForm(forms.ModelForm):
    blog_name = forms.CharField(label='博客名称')
    admin_email = forms.EmailField(label='你的邮箱')
    other = forms.CharField(
        label='其他信息',
        widget=forms.Textarea(attrs={'rows': 3, 'cols': 80}))

    class Meta:
        model = Aboutme
        fields = ['blog_name', 'admin_email', 'other']

blog_articles/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect, Http404, HttpResponse
from django.db.models import Count
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from myuser.models import allUser
from .models import Article, Category, Aboutme, Tag, Comments, Friends
from .forms import CommentForm, ArticleForm, CategoryForm, TagForm, ReplyForm
from haystack.forms import SearchForm
from django.core.urlresolvers import reverse


class IndexView(ListView):
    """博客主页文章列表"""
    # template_name = "blog_articles/new/index.html"
    template_name = 'blog_articles/new/index.html'
    context_object_name = "article_list"

    # 返回文章,前5篇
    def get_queryset(self):
        article_list = Article.objects.filter(status='p').order_by('-create_time')[0:5]
        return article_list

    def get_context_data(self, **kwargs):
        # 增加额外的数据，这里返回一个文章分类，以字典的形式
        # 显示前五项最新修改的分类
        kwargs['category_list'] = Category.objects.order_by('-modified_time')[0:5]
        # 标签列表
        kwargs['tag_list'] = Tag.objects.all().order_by('name')
        kwargs['comment_list'] = Comments.objects.all().order_by('-published_time')[:5]
        return super(IndexView, self).get_context_data(**kwargs)


class ArticleDetailView(DetailView):
    """文章详情页视图"""
    model = Article

    template_name = "blog_articles/new/detail.html"

    context_object_name = "article"

    pk_url_kwarg = 'article_id'

    # get_object() 返回该视图要显示的对象
    def get_object(self):
        context = super(ArticleDetailView, self).get_object()
        return context

    def get_context_data(self, **kwargs):
        kwargs['category_list'] = Category.objects.all().order_by('name')
        kwargs['form'] = CommentForm()
        kwargs['comment_list'] = self.object.comments_set.all()
        return super(ArticleDetailView, self).get_context_data(**kwargs)


def detail(request, article_id):
    article = Article.objects.get(id=article_id)
    article.add_reading()
    category_list = Category.objects.all().order_by('name')
    form = CommentForm()
    replyform = ReplyForm()
    comment_list = article.comments_set.all()
    context = {'article': article,
               'category_list': category_list,
               'form': form,
               'replyform': replyform,
               'comment_list': comment_list}
    return render(request, 'blog_articles/new/detail.html', context)


class CategoryView(ListView):
    """单个分类下的文章列表视图--类形式"""

    template_name = "blog_articles/category.html"
    # 指定需要渲染的模板

    context_object_name = "article_list"

    # 指定模板中需要使用的上下文对象的名字

    def get_queryset(self):
        # get_queryset 的作用已在第一篇中有介绍，不再赘述
        article_list = Article.objects.filter(category=self.kwargs['category_id'], status='p')
        # 使用了分类的id作为关键字参数（category_id）传递给了CategoryView，传递的参数在kwargs属性中获取。
        return article_list

    # 给视图增加额外的数据
    def get_context_data(self, **kwargs):
        # 增加一个category_list,用于在页面显示所有分类，按照名字排序
        kwargs['category_list'] = Category.objects.all().order_by('name')
        # 获取正确的分类id，以便在标题栏正确显示分类名称
        kwargs['category'] = Category.objects.get(id=self.kwargs['category_id'])
        # 统计分类下的文章数量
        kwargs['count'] = Category.objects.annotate(num=Count('article'))
        return super(CategoryView, self).get_context_data(**kwargs)


class Tagview(ListView):
    template_name = 'blog_articles/tag.html'

    context_object_name = 'article_list'

    def get_queryset(self):
        article_list = Article.objects.filter(tag=self.kwargs['tag_id'], status='p')
        return article_list

    def get_context_data(self, **kwargs):
        kwargs['tag_list'] = Tag.objects.all().order_by('name')
        kwargs['tag'] = Tag.objects.get(id=self.kwargs['tag_id'])
        return super(Tagview, self).get_context_data(**kwargs)


# 单个分类下的文章列表视图-次选-函数形式
# def categoryview(request, category_id):
#     category = Category.objects.get(id=category_id)
#     article_list = category.article_set.order_by('-modified_time')
#     context = {'category': category, 'article_list': article_list}
#     return render(request, 'blog_articles/category.html', context)

def aboutme(request):
    """显示关于博客的页面"""

    # 只取第一条数据
    about = Aboutme.objects.all()[0]
    friend_link_list = Friends.objects.all()
    context = {'about': about, 'friend_link_list': friend_link_list, }
    return render(request, 'blog_articles/aboutme.html', context)


def showcategories(request):
    """分类主页面"""
    # 分类下没有文章不显示
    category_list = Category.objects.all()
    context = {'category_list': category_list}
    return render(request, 'blog_articles/new/categories.html', context)


def archive(request, year, month):
    """日期归档视图函数"""
    string = str(year) + '-' + str(month)
    article_list = Article.objects.filter(create_time__startswith=string)
    category_list = Category.objects.all().order_by('-modified_time')[0:5]
    tag_list = Tag.objects.all().order_by('name')
    context = {'article_list': article_list, 'category_list': category_list,
               'tag_list': tag_list}
    return render(request, 'blog_articles/new/index.html', context)


# @login_required
# def write_comments(request, article_id):
#     """评论"""
#     if request.method != 'POST':
#         form = CommentForm()
#
#     else:
#         form = CommentForm(request.POST)
#         if form.is_valid():
#             article = Article.objects.get(id=article_id)
#             user = request.user
#             comment = form.save(commit=False)
#             comment.article = article
#             comment.user = user
#             form.save()
#             # return redirect(to='article', id=article_id)
#             return redirect('blog:detail', article_id=article_id)
#
#     return redirect('blog:detail', article_id=article_id)

@login_required
def write_comments(request, article_id):
    """评论"""
    if request.method == 'POST':
        user = request.user
        content = request.POST['content']
        article = Article.objects.get(id=article_id)
        Comments.objects.create(user=user, content=content, article=article)
        print(user, content, article_id)
        return HttpResponse('发送成功')
    else:
        return HttpResponse('发送失败')


@login_required
def reply_comment(request, comment_id):
    """回复评论"""
    related = Comments.objects.get(id=comment_id)
    article = related.article
    article_id = article.id
    if request.method != "POST":
        form = ReplyForm()
    else:
        form = ReplyForm(data=request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            user = request.user
            comment.article = article
            comment.related = related
            comment.user = user
            form.save()
            realcomment = Comments.objects.filter(article=article).order_by('-published_time')[0]
            url = "/article/" + str(article.id) + "#commentboard" + str(realcomment.id)
            return HttpResponseRedirect(redirect_to=url)
            # return redirect(to='blog:detail', article_id=article_id)
    return HttpResponse('<script>history.back()</script>')


# @login_required
# def reply_comment(request, comment_id):
#     """回复评论"""
#     if request.method == "POST":
#         related = Comments.objects.get(id=comment_id)
#         article = related.article
#         user = request.user
#         content = request.POST['reply']
#         print(related, article, user, content)
#         # Comments.objects.create(user=user, article=article, content=content, related=related)
#         # return HttpResponse('ok')



@login_required
def edit_comment(request, comment_id):
    """修改评论"""
    comment = Comments.objects.get(id=comment_id)
    article_id = comment.article_id
    if request.method != "POST":
        form = CommentForm(instance=comment)
    else:
        form = CommentForm(instance=comment, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('blog:detail', article_id=article_id)
    context = {'comment_form': form, 'comment': comment, 'article': article_id}
    return render(request, 'blog_articles/edit_comment.html', context)


@login_required
def delete_comment(request, comment_id):
    """文章详情页删除评论"""
    comment = Comments.objects.get(id=comment_id)
    article_id = comment.article_id
    comment.delete()
    return redirect('blog:detail', article_id=article_id)


def search_article(request):
    """文章搜索"""
    keyword = request.GET['q']
    # haystack.SearchForm
    form = SearchForm(request.GET)
    articles = form.search()
    messages = '关键字 \'{}\' 搜索结果'.format(keyword)
    context = {
        'articles': articles,
        'messages': messages,
    }
    return render(request, 'blog_articles/article_search.html', context)


def edit_comment(request, comment_id):
    """文章详情页修改评论"""
    comment = Comments.objects.get(id=comment_id)
    article_id = comment.article_id
    if request.method != "POST":
        form = CommentForm(instance=comment)
    else:
        form = CommentForm(instance=comment, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('blog:detail', article_id=article_id)
    context = {'comment_form': form, 'comment': comment, 'article': article_id}
    return render(request, 'blog_articles/edit_comment.html', context)

blog_articles/templates/blog_articles/article.html
{% extends 'blog_articles/base.html' %}
<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{{ article.title }}{% endblock %}</title>
    {% load dractags %}
    {% block extrastyle %}
        <style>
            /*直接从amazeui.css里面套用响应式图片，实现根据屏幕分辨率变化*/
            #mainbody img {
                display: block;
                max-width: 100%;
                height: auto;
            }

            /*解决使用highlight.js造成的白边问题*/
            pre {
                padding: 0px;
            }
        </style>
    {% endblock %}
    {% block extrahead %}
        <!--导入highlight.js实现代码高亮-->
        <script src="//cdn.bootcss.com/highlight.js/9.10.0/highlight.min.js"></script>
        <link href="//cdn.bootcss.com/highlight.js/9.10.0/styles/agate.min.css" rel="stylesheet">
        <script src="//cdn.bootcss.com/jquery.qrcode/1.0/jquery.qrcode.min.js"></script>
    {% endblock %}
</head>
<body>
{% block content %}

    <div class="am-g am-g-fixed">
        <!--文章详细主体-->
        <div class="am-u-lg-12 am-u-md-10 am-u-sm-10 am-u-lg-centered am-u-md-centered am-u-sm-centered">
            <br>
            <!--导航条-->
            <ol class="am-breadcrumb">
                <li><a href="{% url 'blog:index' %}" class="am-icon-home am-icon-sm">首页</a></li>
                <li><a href="{% url 'blog:categories' %}">分类</a></li>
                <!--before:article.category_id是article的外键-->
                <!--after: article.category.id 看起来易懂些。。-->
                <li><a href="{% url 'blog:category' article.category.id %}">{{ article.category }}</a></li>
                <li>{{ article.title }}</li>
            </ol>

            <div style="background-color: inherit">
                <!--文章标题-->
                <h1 style="font-family: NotoSans; font-size: 350%; text-align: center">{{ article.title }}</h1>
                <!--作者和最后修改时间-->
                <h6 style="font-family: NotoSans; text-align: center">
                    由&nbsp;{{ article.author }}&nbsp;最后修改于&nbsp;{{ article.modified_time }}
                </h6>
                <!--文章标签-->
                <p>
                    <span class="am-icon-tags am-icon-md"></span>
                    <!--使用for循环才能显示出标签，否则获取不了数据-->
                    {% for tag in article.tag.all %}
                        <a href="{% url 'blog:tag' tag.pk %}">{{ tag }}</a>&nbsp;
                    {% endfor %}
                </p>
            </div>
            <div class="articlefont" style="font-family: NotoSans, SansSerif" id="mainbody">
                {{ article.body | safe_markdown }}
            </div>
            {% if user.is_superuser %}
                <div align="center">
                    <a href="{% url 'blog:edit_article' article.id %}"
                       style="color: inherit">
                        <button class="am-btn am-btn-warning">编辑文章</button>
                    </a>
                </div>
            {% endif %}

            <hr>

            <div style="display:inline">
                <button type="button" class="am-btn am-radius color-modal-btn-blue"
                        data-am-modal="{target: '#doc-modal-1'}"
                        style="float:left">
                    扫码阅读
                </button>
                &nbsp;&nbsp;
                <!--百度分享按钮-->
                <!--http://share.baidu.com/-->
                <div class="bdsharebuttonbox" style="float:left">
                    {#                <a href="#" class="bds_more" data-cmd="more"></a>#}
                    <a href="#" class="bds_qzone" data-cmd="qzone" title="分享到QQ空间"></a>
                    <a href="#" class="bds_tsina" data-cmd="tsina" title="分享到新浪微博"></a>
                    <a href="#" class="bds_weixin" data-cmd="weixin" title="分享到微信"></a>
                    <a href="#" class="bds_fbook" data-cmd="fbook" title="分享到Facebook"></a>
                    <a href="#" class="bds_douban" data-cmd="douban" title="分享到豆瓣网"></a>
                </div>
                <script>
                    window._bd_share_config = {
                        "common": {
                            "bdSnsKey": {},
                            "bdText": "",
                            "bdMini": "1",
                            "bdMiniList": false,
                            "bdPic": "",
                            "bdStyle": "1",
                            "bdSize": "24"
                        }, "share": {}
                    };
                    with (document)0[(getElementsByTagName('head')[0] || body).appendChild(createElement('script')).src = '/static/api/js/share.js?v=89860593.js?'];
                </script>
            </div>

            <br><br>

            {% if user.is_authenticated %}
                <div>
                    <form action="{% url 'blog:comment' article.id %}" method="post">
                        {% csrf_token %}
                        <div class="am-form-group">
                            <label>请输入您的评论</label><br>
                            {{ form.content }}
                        </div>
                        <button class="am-btn am-btn-success" type="submit">提交评论</button>
                    </form>
                </div>
            {% else %}
                <div class="am-panel am-panel-default">
                    <div class="am-panel-bd">真正的粉丝，即使我什么也不说 ---->>&nbsp;
                        <a href="{% url 'account:login' %}">登录</a>&nbsp;
                        <a href="{% url 'account:register' %}">注册</a>
                    </div>
                </div>
            {% endif %}

            <br>

            <div>
                <ul class="am-comments-list">
                    {% for comment in comment_list %}
                        <li class="am-comment ">
                            <img class="am-comment-avatar" alt="" src="/media/{{ comment.user.avatar }}"/>
                            <div class="am-comment-main ">
                                <header class="am-comment-hd">
                                    <div class="am-comment-meta" style="background-color: #f5f5ff">
                                        <a href="{% url 'account:profile' comment.user_id %}">{{ comment.user }}</a>
                                        评论于
                                        {{ comment.published_time }}
                                        <div style="float: right">
                                            {% if user.id == comment.user.id %}
                                                <a href="{% url 'blog:edit_comment' comment.id %}">
                                                    <i class="am-icon-edit am-icon-sm" title="编辑评论"></i>
                                                </a>
                                                &nbsp;
                                                <a href="{% url 'blog:delete_comment' comment.id %}">
                                                    <i class="am-icon-close am-icon-sm" title="删除评论"></i>
                                                </a>
                                            {% endif %}
                                        </div>
                                    </div>
                                </header>
                                <div class="am-comment-bd"
                                     style="background-color: rgba(211,255,245,0.12)">{{ comment.content }}
                                    <div>
                                        <a href=""><span class="am-icon-reply"></span></a>
                                    </div>
                                </div>
                                <!-- 评论内容 -->
                            </div>
                        </li>
                    {% endfor %}
                </ul>
            </div>


            <!--Modal隐藏窗口,文章二维码-->
            <div class="am-modal am-modal-no-btn color-modal-style color-modal-style-blue" tabindex="-1"
                 id="doc-modal-1">
                <div class="am-modal-dialog">
                    <div class="color-modal-style-head am-text-middle">
            <span class="color-modal-style-head-title ">
                文章二维码
            </span>
                    </div>
                    <div class="am-modal-hd">
                        <script>document.write(document.URL)</script>
                        <a href="javascript: void(0)" class="am-close am-close-spin  color-modal-style-close"
                           data-am-modal-close>×</a>
                    </div>
                    <div class="am-modal-bd">
                        <div align="center" id="qrcode"></div>
                        <script type="text/javascript">
                            thisURL = document.URL;
                            jQuery('#qrcode').qrcode({width: 150, height: 150, text: thisURL});
                        </script>

                    </div>
                    <div class="color-modal-style-btn">
                        <button type="button" class="am-btn am-radius" data-am-modal-close>好的</button>
                    </div>

                </div>
            </div>

        </div>
    </div>
    <br>



    <br>

    <script>hljs.initHighlightingOnLoad();</script>
{% endblock content %}
</body>
</html>

blog_articles/templates/blog_articles/category.html
{% extends 'blog_articles/base.html' %}
<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{{ category }}{% endblock %}</title>
    {% load markdown_deux_tags %}
    {% block extrastyle %}
        <style>
            h5#bigger {
                font-weight: bold;
                color: rgba(35, 51, 51, 0.73);
            }

            #just-bigger {
                font-size: 110%;
            }

            .trans {
                background-color: transparent;
            }

            .noborder {
                border-top: none;
                border-bottom: none;
                border-left: none;
                border-right: none;
            }
        </style>
    {% endblock extrastyle %}
    {% block extrahead %}
    {% endblock extrahead %}
    {#draceditor的渲染标签#}
    {% load dractags %}
</head>
<body>
{% block content %}
    <br>
    <div class="am-g am-g-fixed">
        <div class="am-u-sm-12 am-u-md-12 am-u-lg-12 am-u-sm-centered am-u-md-centered">
            <div class="color-breadcrumb" id="just-bigger">
            <span><a class="color-breadcrumb-link" href="{% url 'blog:index' %}"><i type="home"
                                                                                    class="am-icon-home"></i>首页</a>
                <span class="color-breadcrumb-separator">/</span></span>
                <span><a class="color-breadcrumb-link" href="{% url 'blog:categories' %}">分类</a>
                <span class="color-breadcrumb-separator">/</span></span>
                <span><span class="color-breadcrumb-link">{{ category.name }}</span><span
                        class="color-breadcrumb-separator">/</span></span>
            </div>
        </div>

        <br>
        <br>
        <div class="am-u-sm-10 am-u-md-10 am-u-lg-12 am-u-sm-centered am-u-md-centered">
            {% for article in article_list %}
                <article class="am-article">
                    <div class="am-article-hd">
                        <h1 class="am-article-title">
                            <a href="{% url 'blog:detail' article.pk %}"> {{ article.title }}</a></h1>
                        <div class="am-article-meta">
                            <h5 id="bigger">
                                <span class="am-icon-male am-icon-md"></span>&nbsp;&nbsp;{{ article.author }}&nbsp;<br>
                                <span class="am-icon-clock-o am-icon-md"></span>&nbsp;&nbsp;{{ article.create_time }}&nbsp;&nbsp;<br>
                                <span class="am-icon-edit am-icon-md"></span>&nbsp;&nbsp;{{ article.modified_time }}
                            </h5>
                        </div>
                    </div>

                    <div class="am-article-bd">
                        {% if article.abstract == None %}
                            <p></p>
                        {% else %}
                            <div class="am-article-lead trans noborder">
                                <h5>文章摘要:</h5>
                                {{ article.abstract }}
                                <p><a href="{% url 'blog:detail' article.pk %}">阅读全文>>></a></p>
                            </div>
                        {% endif %}
                        <div class="am-panel am-panel-default noborder">
                            <footer class="am-panel-footer trans">
                                <p><span class="am-icon-star am-icon-xs"></span>&nbsp;<a
                                        href="{% url 'blog:category' article.category.id %}">{{ article.category }}</a>
                                </p>
                                <p>
                                    <span class="am-icon-tags am-icon-xs"></span>
                                    <!--使用for循环才能显示出标签，否则获取不了数据-->
                                    {% for tag in article.tag.all %}
                                        <a href="{% url 'blog:tag' tag.id %}">{{ tag }}</a>&nbsp;
                                    {% endfor %}
                                </p>
                            </footer>
                        </div>
                    </div>
                </article>
                <hr class="am-article-divider">

            {% endfor %}
            <h1>没有更多了。。。</h1>
        </div>
    </div>
{% endblock content %}
</body>
</html>