blog/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from . import settings

urlpatterns = [
                  # 引用blog_articles里面的urls.py
                  url(r'', include('blog_articles.urls', namespace='blog')),
                  url(r'^admin/', include(admin.site.urls)),
                  url(r'^draceditor/', include('draceditor.urls')),
                  url(r'^board/', include('msb.urls', namespace='msb')),
                  url(r'^account/', include('myuser.urls', namespace='account')),
                  url(r'^haystacksearch/', include('haystack.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL,
                                                                                         document_root=settings.STATIC_ROOT)

blog_articles/urls.py
from django.conf.urls import url, handler404, handler500
from django.conf.urls.static import static
from django.conf import settings
from . import views, rss
from . import manage_views as manage

handler404 = 'manage.page_not_found'

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^aboutme$', views.aboutme, name='aboutme'),
    url(r'^categories$', views.showcategories, name='categories'),
    url(r'^categories/(?P<category_id>\d+)$',
        views.CategoryView.as_view(), name='category'),
    # 文章详情
    url(r'^article/(?P<article_id>\d+)$',
        views.detail, name='detail'),
    url(r'^tag/(?P<tag_id>\d+)$', views.Tagview.as_view(), name='tag'),
    url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$',
        views.archive, name='archive'),
    # 写评论
    url(r'^article/(?P<article_id>\d+)/comment/$',
        views.write_comments, name='comment'),
    # 删除评论
    url(r'^delete_comment/(?P<comment_id>\d+)/$',
        views.delete_comment, name='delete_comment'),
    # 回复评论
    url(r'^reply_comment/(?P<comment_id>\d+)/$',
        views.reply_comment, name='reply_comment'),
    # 修改评论
    url(r'^edit_comment/(?P<comment_id>\d+)/$',
        views.edit_comment, name='edit_comment'),
    url(r'^search/$', views.search_article, name='search'),
    # 下面是管理后台的
    url(r'^myarticles/', manage.myarticles, name='myarticles'),
    url(r'change_titlephoto/(?P<article_id>\d+)/$', manage.change_titlephoto, name='titlephoto'),
    url(r'^delete_article/(?P<article_id>\d+)/$', manage.delete_article, name='delete_article'),
    url(r'^article_comment/(?P<article_id>\d+)/$', manage.article_comment, name='article_comment'),
    url(r'^manage_comment/edit/(?P<comment_id>\d+)/$', manage.edit_comment, name='manage_c_edit'),
    url(r'^manage_comment/delete/(?P<comment_id>\d+)/$', manage.delete_comment, name='manage_c_del'),
    url(r'^new_article/$', manage.new_article, name='new_article'),
    url(r'^edit_article/(?P<article_id>\d+)$',
        manage.edit_article, name='edit_article'),
    url(r'^management/$', manage.management_index, name='management'),
    url(r'^category_list/$', manage.manage_category, name='category_list'),
    url(r'^tag_list/$', manage.manage_tags, name='tag_list'),
    url(r'^edit_category/(?P<category_id>\d+)', manage.edit_category, name='edit_category'),
    url(r'^edit_tag/(?P<tag_id>\d+)', manage.edit_tag, name='edit_tag'),
    url(r'^delete_category/(?P<category_id>\d+)', manage.delete_category, name='delete_category'),
    url(r'^delete_tag/(?P<tag_id>\d+)', manage.delete_tag, name='delete_tag'),
    # 友链
    url(r'^link_list/$', manage.friendlink, name='link_list'),
    url(r'^delete_link/(?P<friends_id>\d+)/$', manage.delete_friends, name='del_link'),
    # 修改关于博客
    url(r'^manage_aboutme/(?P<id>\d+)$', manage.edit_aboutme, name='edit_aboutme'),
    # rss
    url(r'^latest/feed/$', rss.LatestArticle(), name='rss'),
]

msb/urls.py
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings
from . import views

urlpatterns = [
                  url(r'^$', views.MessageBoard, name='board'),
                  url(r'^manage/$', views.msb_manage, name='manage'),
                  url(r'^delete/(?P<message_id>\d+)/$', views.msb_manage, name='delete'),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

myuser/urls.py
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings
from . import views

urlpatterns = [
                  url(r'^login/$', views.user_login, name='login'),
                  url(r'^logout/$', views.user_logout, name='logout'),
                  url(r'^register/$', views.user_register, name='register'),
                  url(r'^profile/(?P<user_id>\d+)$', views.profile, name='profile'),
                  url(r'^avatar/(?P<user_id>\d+)$', views.change_avatar, name='change_avatar'),
                  # 私信
                  url(r'^post_private/(?P<receiver_id>\d+)/$', views.send_messages, name='send_private'),
                  # 用户管理
                  url(r'^userlist/$', views.userlist, name='userlist'),
                  url(r'^disable/(?P<user_id>\d+)/$', views.disabled_user, name='disable'),
                  url(r'^able/(?P<user_id>\d+)/$', views.abled_user, name='able'),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blog_articles/models.py
from django.db import models
from django.conf import settings
# 导入自带的User，为文章作者显示正确的用户名
from django.contrib.auth.models import User
from draceditor.models import DraceditorField


# Create your models here.

# 创建博客主题模型
class Article(models.Model):
    """博客主体，内包含文章，编者，发布状态与时间等等"""

    # Field.choices
    # 选择器，可以选择
    DRAFT = 'd'
    PUBLISHED = 'p'
    PUBLISH_STATUS_CHOICES = (
        (DRAFT, '草稿'),
        (PUBLISHED, '发布'),
    )

    # 文章标题，max_length为标题最大长度
    # '标题'是一个位置参数，admin后台管理提示符
    title = models.CharField('文章标题', max_length=70, help_text='标题')

    # 文章主体
    # '正文'的作用同上，都只是用于admin管理界面
    # help_text是在admin界面文本框中显示的提示文字
    # 换用DraceEditor来实现Markdown编辑器
    body = DraceditorField('正文', help_text='请编写你的文章')

    # 创建时间
    create_time = models.DateTimeField('创建时间', auto_now_add=True)

    # 修改时间
    modified_time = models.DateTimeField('修改时间', auto_now=True)

    # 文章发布状态，默认值为草稿
    status = models.CharField('发布状态', max_length=1,
                              choices=PUBLISH_STATUS_CHOICES,
                              default=DRAFT)

    # 文章摘要,长度100个字符
    # null 是针对数据库的，当null=True, 表示数据库的该字段可以为空。
    # blank 是针对表单的，当blank=True，表示你的表单填写该字段的时候可以不填
    abstract = models.CharField('文章摘要', max_length=100, blank=True, null=True,
                                help_text='摘要，可填选项')
    # 文章被浏览次数
    # PositiveIntegerField，指定这个数必须为0以上的正整数，范围from 0 to 2147483647
    reading = models.PositiveIntegerField('阅读量', default=0)

    # 文章点赞次数
    likes = models.PositiveIntegerField('赞', default=0)

    # 文章被置顶状态（废弃）
    # BooleanField : A true/false field.不设定值的话默认是null，故设置默认值
    # top = models.BooleanField('置顶', default=False)

    # 文章分类
    # verbose_name:A human-readable name for the field. 人类可读的名字
    # on_delete有四种选项，这里选择SET_NULL。当删除分类后使相关文章的外键变为空
    category = models.ForeignKey('Category', verbose_name='分类', null=True,
                                 on_delete=models.SET_NULL)

    # 20170408添加
    # 文章标签（从Tag类获取）
    # blank=True 即表示没有标签也可以
    tag = models.ManyToManyField('Tag', blank=True)

    # 文章作者
    # User是django内置的用户模型，
    # 通过 ForeignKey 把文章和User关联起来
    # limit_choice_to 控制只有超级管理员才能是作者，从而把评论者和撰文者分开
    author = models.ForeignKey(settings.AUTH_USER_MODEL, limit_choices_to={'is_superuser': 1})

    titlephoto = models.ImageField(max_length=254, upload_to='photos', default='/default/img2.jpg')

    def add_reading(self):
        self.reading += 1
        self.save(update_fields=['reading'])

    def __str__(self):
        # 显示文章的标题
        return self.title

    class Meta:
        # 告诉Django模型对象返回的记录结果集是依照哪个字段排序的
        # 下面的意思是按照修改日期降序排列
        # modified_time前面没有-号的话，就是按照升序排列
        ordering = ['-modified_time']
        # 在admin主页中显示的名字从Articles变为文章
        verbose_name_plural = '文章'


class Category(models.Model):
    """文章分类"""
    # 分类名称,独一无二
    name = models.CharField('分类名', max_length=20, unique=True)
    # 分类创建时间
    create_time = models.DateTimeField('创建时间', auto_now_add=True)
    # 分类修改时间
    modified_time = models.DateTimeField('修改时间', auto_now=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = '分类'


class Tag(models.Model):
    """文章标签"""
    name = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = '标签'


# 关于博客页面
class Aboutme(models.Model):
    blog_name = models.CharField('博客名称', max_length=50)
    admin_email = models.EmailField()
    other = models.TextField()

    class Meta:
        verbose_name_plural = '关于博客'

    def __str__(self):
        return self.blog_name


class Comments(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='用户')
    article = models.ForeignKey(Article, verbose_name='关联文章')
    content = models.TextField(verbose_name='内容')
    published_time = models.DateTimeField('创建时间', auto_now_add=True)

    # 预留接口
    related = models.ForeignKey('self', default=None, blank=True, null=True,
                                verbose_name='引用')

    def __str__(self):
        if (len(self.content) <= 20):
            return self.content
        else:
            return self.content[:20] + '...'

    class Meta:
        verbose_name_plural = '评论'
        ordering = ['-published_time']


class Friends(models.Model):
    name = models.CharField(max_length=20, verbose_name='名称')
    links = models.URLField('友情链接')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "友情链接"

blog_articles/forms.py
from .models import Article, Category, Tag, Comments, Friends, Aboutme
from myuser.models import allUser
from django import forms
from draceditor.fields import DraceditorFormField, DraceditorWidget


class ReplyForm(forms.ModelForm):
    """回复表单"""
    content = forms.CharField()

    class Meta:
        model = Comments
        fields = ['content']


class CommentForm(forms.ModelForm):
    """评论表单"""
    content = forms.CharField(
        widget=forms.Textarea(attrs={'class': 'color-form-control', 'id': 'commentcontent', 'rows': 3}))

    class Meta:
        model = Comments
        fields = ['content']


class ArticleForm(forms.ModelForm):
    """文章表单"""
    title = forms.CharField(max_length=70)
    author = forms.ModelChoiceField(queryset=allUser.objects.filter(is_superuser=True),
                                    widget=forms.Select(attrs={'data-am-selected': None}))
    category = forms.ModelChoiceField(queryset=Category.objects.all(),
                                      widget=forms.Select(attrs={'data-am-selected': None}))
    tag = forms.ModelMultipleChoiceField(queryset=Tag.objects.all(),
                                         widget=forms.SelectMultiple(
                                             attrs={'multiple': None, 'data-am-selected': "{btnWidth: '50%'}"}))
    abstract = forms.CharField(max_length=100)
    body = forms.CharField(widget=forms.Textarea)

    class Meta:
        model = Article
        fields = ['title', 'author', 'category', 'tag', 'abstract', 'body', 'status']


class TitlePhotoForm(forms.ModelForm):
    titlephoto = forms.ImageField()

    class Meta:
        model = Article
        fields = ['titlephoto']

class CategoryForm(forms.ModelForm):
    """分类表单"""
    name = forms.CharField(max_length=20,
                           widget=forms.TextInput(attrs={'class': 'am-form-field am-round', 'style': 'width:50%'}))

    class Meta:
        model = Category
        fields = ['name']
        labels = {'name': ''}


class TagForm(forms.ModelForm):
    """标签表单"""
    name = forms.CharField(max_length=20,
                           widget=forms.TextInput(attrs={'class': 'am-form-field am-round', 'style': 'width:50%'}))

    class Meta:
        model = Tag
        fields = '__all__'
        labels = {'name': ''}


class LinkForm(forms.ModelForm):
    name = forms.CharField(max_length=20,
                           label='名称',
                           widget=forms.TextInput(attrs={'class': 'am-form-field am-round', 'style': 'width:50%'}))
    links = forms.URLField(label='链接',
                           widget=forms.URLInput(attrs={'class': 'am-form-field am-round', 'style': 'width:50%'}))

    class Meta:
        model = Friends
        fields = ['name', 'links']
        labels = {'name': '名称', 'links': '链接'}


class AboutForm(forms.ModelForm):
    blog_name = forms.CharField(label='博客名称')
    admin_email = forms.EmailField(label='你的邮箱')
    other = forms.CharField(
        label='其他信息',
        widget=forms.Textarea(attrs={'rows': 3, 'cols': 80}))

    class Meta:
        model = Aboutme
        fields = ['blog_name', 'admin_email', 'other']

blog_articles/templates/blog_articles/new/categories.html
{% extends 'blog_articles/base.html' %}
<!doctype html>
<html>
<head>
    <title>{% block title %}分类归档{% endblock %}</title>
    {% block extrastyle %}
        <style>
            body {
                background-color: rgba(225, 225, 225, 0.23);
            }
        </style>
    {% endblock %}
</head>
{% block content %}
    <body id="blog-article-sidebar">
    <!-- header start -->
    <header class="am-g am-g-fixed blog-fixed blog-text-center blog-header">
        <div class="am-u-sm-8 am-u-sm-centered">
            {# <img width="100" src="/static/amaze-assets/i/hdIm.jpg" alt="Blog Logo" style="vertical-align: middle"/>&nbsp;#}
            <h2 class="modfont" style="font-size: 200%">My Blog</h2>
        </div>
    </header>
    <hr>
    <!-- header end -->
    <hr>
    <nav class="am-g am-g-fixed blog-fixed blog-content">
        <button class="am-topbar-btn am-topbar-toggle am-btn am-btn-sm am-btn-success am-show-sm-only blog-button"
                data-am-collapse="{target: '#blog-collapse'}"><span class="am-sr-only">导航切换</span> <span
                class="am-icon-bars"></span></button>

        <div class="am-collapse am-topbar-collapse" id="blog-collapse">
            <ul class="am-nav am-nav-pills am-topbar-nav">
                <li><a href="{% url 'blog:index' %}">最新文章</a></li>
                <li class="am-active"><a href="{% url 'blog:categories' %}">分类</a></li>
                <li><a href="{% url 'msb:board' %}">留言板</a></li>
                <li><a href="{% url 'blog:aboutme' %}">关于博客</a></li>
                {#
                <li><a href="{% url 'blog:rss' %}"><span class="am-icon-rss"></span>RSS Feed</a></li>
                #}
                {% if user.is_authenticated %}
                    <li class="am-dropdown" data-am-dropdown="">
                        <a class="am-dropdown-toggle" data-am-dropdown-toggle="" href="">
                            您好,{{ user.username }}<span class="am-icon-caret-down"></span>
                        </a>
                        <ul class="am-dropdown-content">
                            <li><a href="{% url 'account:logout' %}">注销</a></li>
                            <li><a href="{% url 'account:profile' user.id %}">个人资料</a></li>
                        </ul>
                    </li>
                {% else %}
                    <li><a href="{% url 'account:login' %}">登录</a></li>
                {% endif %}

            </ul>

            <form class="am-topbar-form am-topbar-right am-form-inline" action="{% url 'blog:search' %}" method="get"
                  role="search">
                <div class="am-form-group">
                    <input type="text" name="q" class="am-form-field am-input-sm" placeholder="搜索">
                </div>
                <button type="submit" class="am-btn am-btn-default am-btn-sm"><span class="am-icon-search"></span>
                </button>
            </form>
        </div>
    </nav>
    <hr>
    <!-- content srart -->
    <div class="am-g am-g-fixed blog-fixed blog-content">
        <div class="am-u-sm-12">
            <h1 class="blog-text-center">-- 分类归档 --</h1>
        </div>
        <div>

            <div class="timeline-year">
                {% for category in category_list %}
                    <ul>
                        <h3>{{ category }}</h3>
                        {% for article in category.article_set.all %}
                            <li>
                                <span class="am-u-sm-12 am-u-md-2 timeline-span">{{ article.create_time| date }}</span>
                                <span class="am-u-sm-12 am-u-md-6"><a
                                        href="{% url 'blog:detail' article.id %}">{{ article.title }}</a></span>
                                <span class="am-u-sm-4 am-u-md-2 am-hide-sm-only">{{ article.author }}</span>
                                <span class="am-u-sm-4 am-u-md-2 am-hide-sm-only">
                                {% for tag in article.tag.all %}
                                    <a href="{% url 'blog:tag' tag.id %}">{{ tag }}&nbsp;</a>
                                {% endfor %}
                            </span>
                            </li>
                        {% endfor %}
                        <br><br>
                    </ul>

                {% endfor %}
            </div>


        </div>

    </div>
    <!-- content end -->
    </body>
{% endblock %}
</html>

blog_articles/templates/blog_articles/new/datetime.html
{% extends 'blog_articles/new/base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}日期归档{% endblock %}</title>
</head>
<body>
{% block content %}
    <div class="am-g am-g-fixed blog-fixed blog-content">
        <div class="am-u-sm-12">
            <div class="timeline-year">
                <ul></ul>
            </div>
        </div>
    </div>
{% endblock content %}
</body>
</html>

blog_articles/templates/blog_articles/new/index.html
{% extends 'blog_articles/base.html' %}
{% load blog_tags %}
<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}主页{% endblock %}</title>
    {% load markdown_deux_tags %}
    {% block extrastyle %}
        <style>
            .contactbtn {
                width: 50px;
                height: 50px;
            }

            body {
                background-color: rgba(225, 225, 225, 0.23);
            }

            h5#bigger {
                font-weight: bold;
                color: rgba(35, 51, 51, 0.73);
            }

            .pag li {
                float: left;
                list-style: none;
            }

            #title {
                text-align: center;
                font-family: NotoSans, SansSerif;
                font-size: 250%;
            }

            #noborder {
                border: hidden;
            }

            .blog-sidebar-widget {
                padding: 0 2rem;
                margin-bottom: 4rem;
                text-align: center;
            }

            .blog-bor {
                border: 1px solid #e5e5e5;
            }

            .roundavatar {
                width: 32px;
                height: 32px;
                border-radius: 50%;
                border: 1px solid transparent;
            }


        </style>
    {% endblock extrastyle %}
    {% block extrahead %}
        <link rel="stylesheet" href="">
    {% endblock extrahead %}
    {#draceditor的渲染标签#}
    {% load dractags %}
    {% load el_pagination_tags %}
</head>
{% block content %}
    <body>
    <header class="am-g am-g-fixed blog-fixed blog-text-center blog-header">
        <div class="am-u-sm-8 am-u-sm-centered">
            {# <img width="100" src="/static/amaze-assets/i/hdIm.jpg" alt="Blog Logo" style="vertical-align: middle"/>&nbsp;#}
            <h2 class="modfont" style="font-size: 200%">My Blog</h2>
        </div>
    </header>
    <hr>

    <nav class="am-g am-g-fixed">
        <button class="am-topbar-btn am-topbar-toggle am-btn am-btn-sm am-btn-success am-show-sm-only blog-button"
                data-am-collapse="{target: '#blog-collapse'}"><span class="am-sr-only">导航切换</span> <span
                class="am-icon-bars"></span></button>

        <div class="am-collapse am-topbar-collapse" id="blog-collapse">
            <ul class="am-nav am-nav-pills am-topbar-nav">
                <li class="am-active"><a href="{% url 'blog:index' %}">最新文章</a></li>
                <li><a href="{% url 'blog:categories' %}">分类</a></li>
                <li><a href="{% url 'msb:board' %}">留言板</a></li>
                <li><a href="{% url 'blog:aboutme' %}">关于博客</a></li>
                {#
                <li><a href="{% url 'blog:rss' %}"><span class="am-icon-rss"></span>RSS Feed</a></li>
                #}
                {% if user.is_authenticated %}
                    <li class="am-dropdown" data-am-dropdown="">
                        <a class="am-dropdown-toggle" data-am-dropdown-toggle="" href="">
                            您好,{{ user.username }}<span class="am-icon-caret-down"></span>
                        </a>
                        <ul class="am-dropdown-content">
                            <li><a href="{% url 'account:logout' %}">注销</a></li>
                            <li><a href="{% url 'account:profile' user.id %}">个人资料</a></li>
                        </ul>
                    </li>
                {% else %}
                    <li><a href="{% url 'account:login' %}">登录</a></li>
                {% endif %}
                {% if user.is_superuser %}
                    <li><a href="{% url 'blog:management' %}">后台管理</a></li>
                {% endif %}

            </ul>

            <form class="am-topbar-form am-topbar-right am-form-inline" action="{% url 'blog:search' %}" method="get"
                  role="search">
                <div class="am-form-group">
                    <input type="text" name="q" class="am-form-field am-input-sm" placeholder="搜索">
                </div>
                <button type="submit" class="am-btn am-btn-default am-btn-sm"><span class="am-icon-search"></span>
                </button>
            </form>
        </div>
    </nav>

    <div class="am-g am-g-fixed">
        <br>
        <!--文章列表-->
        <div class="am-u-md-8">
            {% for article in article_list %}
                <article class="am-g blog-entry-article">
                    <div class="am-u-lg-6 am-u-md-12 am-u-sm-12 blog-entry-img">
                        <img src="{{ article.titlephoto.url }}" alt="" class="am-u-sm-12">
                    </div>
                    <div class="am-u-lg-6 am-u-md-12 am-u-sm-12 blog-entry-text">
                        <a href="{% url 'blog:category' article.category.id %}"
                           class="blog-color">{{ article.category }} &nbsp;</a>
                        <a href="{% url 'account:profile' article.author.id %}"> @{{ article.author }} &nbsp;</a>
                        <span>{{ article.create_time|date:'Y-m-d' }}&nbsp;&nbsp;&nbsp;</span>
                        <span class="am-icon-eye">&nbsp;{{ article.reading }}</span>
                        <h1 style="font-size: xx-large"><a
                                href="{% url 'blog:detail' article.id %}">{{ article.title }}</a></h1>
                        <p>{{ article.abstract }}</p>
                    </div>
                </article>
                <br>
            {% endfor %}
        </div>

        <!--侧边栏-->
        <div class="am-u-md-4">

            <div class="blog-sidebar-widget blog-bor" align="center">
                <h2 class="blog-text-center blog-title" style="background-color: "><span>热门分类</span></h2>
                <ul>
                    {% for category in category_list %}
                        <li style="list-style-type: none;text-align: justify"><h3 style="font-size: 2rem"><a
                                href="{% url 'blog:category' category.id %}">{{ category.name }}</a></h3></li>
                    {% endfor %}
                </ul>
                <a href="{% url 'blog:categories' %}">查看更多>>></a>
                <br><br>
            </div>

            <div>

                <div class="blog-clear-margin blog-sidebar-widget blog-bor am-g ">
                    <h2 class="blog-title"><span>文章标签</span></h2>
                    <div class="am-u-sm-12 blog-clear-padding" id="tags">
                        {% for tag in tag_list %}
                            <a href="{% url 'blog:tag' tag.pk %}"
                               id="tagcloud"
                               class="blog-tag am-badge am-text-sm">{{ tag }}</a>
                        {% endfor %}
                    </div>
                    <div>
                        <!--随机颜色标签云-->
                        <script>
                            window.onload = function () {
                                var tagcloud = document.getElementById('tags');
                                var oa = tagcloud.getElementsByTagName('a');
                                for (var i = 0; i < oa.length; i++) {
                                    oa[i].style.background = "rgb(" + parseInt(Math.random() * 205) + ","
                                        + parseInt(Math.random() * 205) + ","
                                        + parseInt(Math.random() * 205) + ")";
                                }
                            }
                        </script>
                    </div>
                </div>


                <br>

                <!--联系我面板-->
                <div class="blog-sidebar-widget blog-bor" id="content">
                    <h2 class="blog-text-center blog-title"><span>Contact ME</span></h2>
                    <p>
                        <a href="https://github.com/jerry0734" target="_blank"
                        >
                            <button class="am-btn am-icon-github"></button>
                        </a>
                        <a href="http://weibo.com/jerryxjy" target="_blank"
                        >
                            <button class="am-btn am-icon-weibo"></button>
                        </a>
                        <button class="am-btn am-icon-wechat" data-am-modal="{target: '#mywechat'}"></button>
                        <button class="am-btn am-icon-qq" data-am-modal="{target: '#qq'}"></button>
                    </p>
                </div>

                <div class="blog-sidebar-widget blog-bor" align="center">
                    <h2 class="blog-text-center blog-title"><span>最新评论</span></h2>
                    <ul>
                        {% for comment in comment_list %}
                            <li style="list-style-type: none;">
                                <p align="left"><img src="{{ comment.user.avatar.url }}"
                                                     class="roundavatar">&nbsp;<a
                                        href="{% url 'account:profile' comment.user.id %}">{{ comment.user }}:</a>
                                    <a href="{% url 'blog:detail' comment.article.id %}">{{ comment.content }}</a>
                                </p>
                            </li>
                        {% endfor %}
                    </ul>
                    <br><br>
                </div>
            </div>
        </div>
    </div>

    <!--点击联系我-微信图标弹出的遮罩层-->
    <div class="am-modal am-modal-alert" tabindex="-1" id="mywechat">
        <div class="am-modal-dialog">
            <div class="am-modal-hd">Wechat
                <a href="javascript: void(0)" class="am-close am-close-spin" data-am-modal-close>&times;</a>
            </div>
            <div class="am-modal-bd">
                <p>Wechat ID: xjy_jerry</p>
                <img src="https://jerry002-1252474564.cosgz.myqcloud.com/mmqrcode1492430307368.png" height="50%"
                     width="50%">
            </div>
            <div class="am-modal-footer">
                <span class="am-modal-btn">确定</span>
            </div>
        </div>
    </div>


    <!--点击联系我-QQ图标弹出的遮罩层-->
    <div class="am-modal am-modal-alert" tabindex="-1" id="qq">
        <div class="am-modal-dialog">
            <div class="am-modal-hd">QQ
                <a href="javascript: void(0)" class="am-close am-close-spin" data-am-modal-close>&times;</a>
            </div>
            <div class="am-modal-bd">
                <p>QQ: 891192183</p>
                <img src="https://jerry002-1252474564.cosgz.myqcloud.com/qrcode.jpg" height="50%" width="50%">
            </div>
            <div class="am-modal-footer">
                <span class="am-modal-btn">确定</span>
            </div>
        </div>
    </div>
</body>
{% endblock %}
</html>