blog/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from . import settings

urlpatterns = [
                  # 引用blog_articles里面的urls.py
                  url(r'', include('blog_articles.urls', namespace='blog')),
                  url(r'^admin/', include(admin.site.urls)),
                  url(r'^draceditor/', include('draceditor.urls')),
                  url(r'^board/', include('msb.urls', namespace='msb')),
                  url(r'^account/', include('myuser.urls', namespace='account')),
                  url(r'^haystacksearch/', include('haystack.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL,
                                                                                         document_root=settings.STATIC_ROOT)

blog_articles/urls.py
from django.conf.urls import url, handler404, handler500
from django.conf.urls.static import static
from django.conf import settings
from . import views, rss
from . import manage_views as manage

handler404 = 'manage.page_not_found'

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^aboutme$', views.aboutme, name='aboutme'),
    url(r'^categories$', views.showcategories, name='categories'),
    url(r'^categories/(?P<category_id>\d+)$',
        views.CategoryView.as_view(), name='category'),
    # 文章详情
    url(r'^article/(?P<article_id>\d+)$',
        views.detail, name='detail'),
    url(r'^tag/(?P<tag_id>\d+)$', views.Tagview.as_view(), name='tag'),
    url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$',
        views.archive, name='archive'),
    # 写评论
    url(r'^article/(?P<article_id>\d+)/comment/$',
        views.write_comments, name='comment'),
    # 删除评论
    url(r'^delete_comment/(?P<comment_id>\d+)/$',
        views.delete_comment, name='delete_comment'),
    # 回复评论
    url(r'^reply_comment/(?P<comment_id>\d+)/$',
        views.reply_comment, name='reply_comment'),
    # 修改评论
    url(r'^edit_comment/(?P<comment_id>\d+)/$',
        views.edit_comment, name='edit_comment'),
    url(r'^search/$', views.search_article, name='search'),
    # 下面是管理后台的
    url(r'^myarticles/', manage.myarticles, name='myarticles'),
    url(r'change_titlephoto/(?P<article_id>\d+)/$', manage.change_titlephoto, name='titlephoto'),
    url(r'^delete_article/(?P<article_id>\d+)/$', manage.delete_article, name='delete_article'),
    url(r'^article_comment/(?P<article_id>\d+)/$', manage.article_comment, name='article_comment'),
    url(r'^manage_comment/edit/(?P<comment_id>\d+)/$', manage.edit_comment, name='manage_c_edit'),
    url(r'^manage_comment/delete/(?P<comment_id>\d+)/$', manage.delete_comment, name='manage_c_del'),
    url(r'^new_article/$', manage.new_article, name='new_article'),
    url(r'^edit_article/(?P<article_id>\d+)$',
        manage.edit_article, name='edit_article'),
    url(r'^management/$', manage.management_index, name='management'),
    url(r'^category_list/$', manage.manage_category, name='category_list'),
    url(r'^tag_list/$', manage.manage_tags, name='tag_list'),
    url(r'^edit_category/(?P<category_id>\d+)', manage.edit_category, name='edit_category'),
    url(r'^edit_tag/(?P<tag_id>\d+)', manage.edit_tag, name='edit_tag'),
    url(r'^delete_category/(?P<category_id>\d+)', manage.delete_category, name='delete_category'),
    url(r'^delete_tag/(?P<tag_id>\d+)', manage.delete_tag, name='delete_tag'),
    # 友链
    url(r'^link_list/$', manage.friendlink, name='link_list'),
    url(r'^delete_link/(?P<friends_id>\d+)/$', manage.delete_friends, name='del_link'),
    # 修改关于博客
    url(r'^manage_aboutme/(?P<id>\d+)$', manage.edit_aboutme, name='edit_aboutme'),
    # rss
    url(r'^latest/feed/$', rss.LatestArticle(), name='rss'),
]

msb/urls.py
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings
from . import views

urlpatterns = [
                  url(r'^$', views.MessageBoard, name='board'),
                  url(r'^manage/$', views.msb_manage, name='manage'),
                  url(r'^delete/(?P<message_id>\d+)/$', views.msb_manage, name='delete'),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

myuser/urls.py
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings
from . import views

urlpatterns = [
                  url(r'^login/$', views.user_login, name='login'),
                  url(r'^logout/$', views.user_logout, name='logout'),
                  url(r'^register/$', views.user_register, name='register'),
                  url(r'^profile/(?P<user_id>\d+)$', views.profile, name='profile'),
                  url(r'^avatar/(?P<user_id>\d+)$', views.change_avatar, name='change_avatar'),
                  # 私信
                  url(r'^post_private/(?P<receiver_id>\d+)/$', views.send_messages, name='send_private'),
                  # 用户管理
                  url(r'^userlist/$', views.userlist, name='userlist'),
                  url(r'^disable/(?P<user_id>\d+)/$', views.disabled_user, name='disable'),
                  url(r'^able/(?P<user_id>\d+)/$', views.abled_user, name='able'),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

msb/models.py
from django.db import models


# Create your models here.

class Message(models.Model):
    """留言板model"""

    # 电子邮件
    email = models.EmailField('电子邮件地址')

    # 留言者名称
    author_name = models.CharField('姓名', max_length=20)

    # 内容
    content = models.TextField('正文')

    # 时间
    published_time = models.DateTimeField('发表时间', auto_now_add=True)

    def __str__(self):
        # 控制显示长度
        if len(self.content) <= 25:
            return self.content
        else:
            return self.content[:25] + "..."

    class Meta:
        ordering = ['-published_time']
        verbose_name_plural = '留言'

msb/forms.py
from django import forms
from .models import Message


class MessageForm(forms.ModelForm):
    email = forms.EmailField()

    author_name = forms.CharField(max_length=20)

    content = forms.CharField(widget=forms.Textarea(attrs={'rows': 3}))

    class Meta:
        model = Message
        fields = ['author_name', 'email', 'content']
        # 渲染到表单上的标签，空的表示不生成
        labels = {'content': ""}

msb/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from .models import Message
from .forms import MessageForm


# Create your views here.

def MessageBoard(request):
    if request.method != "POST":
        form = MessageForm()
    else:
        form = MessageForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('msb:board'))

    messages = Message.objects.all().order_by('-published_time')

    context = {'form': form, 'messages': messages}
    return render(request, 'msb/board.html', context)


def msb_manage(request):
    """管理留言板"""
    message_list = Message.objects.all().order_by('-published_time')
    context = {'message_list': message_list}
    return render(request, 'msb/msb_manage.html', context)


def delete_message(request, message_id):
    message = Message.objects.get(id=message_id)
    message.delete()
    return redirect(to='msb:manage')

msb/templates/msb/board.html
{% extends 'blog_articles/base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}留言板{% endblock %}</title>
    {% block extrastyle %}
        <style>
            body {
                background-color: rgba(225, 225, 225, 0.23);
            }
        </style>
    {% endblock %}
    {% load dractags %}
</head>
{% block content %}
    <body>

    <nav class="am-g am-g-fixed" style="padding-top: 20px">
        <button class="am-topbar-btn am-topbar-toggle am-btn am-btn-sm am-btn-success am-show-sm-only blog-button"
                data-am-collapse="{target: '#blog-collapse'}"><span class="am-sr-only">导航切换</span> <span
                class="am-icon-bars"></span></button>

        <div class="am-collapse am-topbar-collapse" id="blog-collapse">
            <ul class="am-nav am-nav-pills am-topbar-nav">
                <li><a href="{% url 'blog:index' %}">最新文章</a></li>
                <li><a href="{% url 'blog:categories' %}">分类</a></li>
                <li class="am-active"><a href="{% url 'msb:board' %}">留言板</a></li>
                <li><a href="{% url 'blog:aboutme' %}">关于博客</a></li>
                {#                <li><a href="{% url 'blog:rss' %}"><span class="am-icon-rss"></span>RSS Feed</a></li>#}
                {% if user.is_authenticated %}
                    <li class="am-dropdown" data-am-dropdown="">
                        <a class="am-dropdown-toggle" data-am-dropdown-toggle="" href="">
                            您好,{{ user.username }}<span class="am-icon-caret-down"></span>
                        </a>
                        <ul class="am-dropdown-content">
                            <li><a href="{% url 'account:logout' %}">注销</a></li>
                            <li><a href="{% url 'account:profile' user.id %}">个人资料</a></li>
                        </ul>
                    </li>
                {% else %}
                    <li><a href="{% url 'account:login' %}">登录</a></li>
                {% endif %}
                {#                {% if user.is_superuser %}#}
                {#                    <li><a href="{% url 'blog:management' %}">后台管理</a></li>#}
                {#                {% endif %}#}

            </ul>

            <form class="am-topbar-form am-topbar-right am-form-inline" action="{% url 'blog:search' %}" method="get"
                  role="search">
                <div class="am-form-group">
                    <input type="text" name="q" class="am-form-field am-input-sm" placeholder="搜索">
                </div>
                <button type="submit" class="am-btn am-btn-default am-btn-sm"><span class="am-icon-search"></span>
                </button>
            </form>
        </div>
    </nav>
    <br>
    <div class="am-g am-g-fixed am-container" align="center">
        <div class="am-u-md-12 am-u-sm-12">
            <h3 class="am-sans-serif ">既然来了，不如留个言呗</h3>
        </div>
    </div>

    <div class="am-g am-g-fixed">
        <div class="">
            <div class="am-u-md-6 am-u-sm-10 am-u-md-centered am-u-sm-centered">
                <form class="am-form " action="{% url 'msb:board' %}" method="post">
                    {% csrf_token %}
                    <div class="am-input-group am-input-group-sm">
                        <label class="am-input-group-label am-warning"><i class="am-icon-user am-icon-fw"></i></label>
                        {{ form.author_name }}
                    </div>
                    <br>
                    <div class="am-input-group am-input-group-sm">
                        <label class="am-input-group-label"><i class="am-icon-envelope am-icon-fw"></i></label>
                        {{ form.email }}
                    </div>
                    <br>
                    <div>
                        <label>您的留言&nbsp;&nbsp;<i class="am-icon-question-circle-o"
                                                  data-am-popover="{theme:'primary',content: '支持部分Markdown语法：**bold**  *italic*  [link](http://example.com)  > 引用', trigger: 'hover focus'}"></i>
                        </label>
                        {{ form.content }}
                    </div>
                    <br>
                    <div align="right">
                        <button name="提交" class="am-btn am-btn-warning">
                            <i class="am-icon-send am-icon-sm">&nbsp;发送</i>
                        </button>
                    </div>
                </form>
            </div>
        </div>

    </div>

    <br>
    <hr data-am-widget="divider" style="" class="am-divider am-divider-dashed">
    <div class="am-g am-g-fixed am-container">
        <h1 style="text-align: center">留言板</h1>
        {% for message in messages %}
            <ul class="am-comments-list">
                <li class="am-comment">
                    <img src="/static/amaze-assets/i/ren.png" alt="" class="am-comment-avatar" width="48" height="48"/>
                    <div class="am-comment-main">
                        <header class="am-comment-hd">
                            <div class="am-comment-meta" style="background-color: ghostwhite">
                                #{{ forloop.revcounter }}&nbsp;由
                                <b class="am-comment-author">{{ message.author_name }}</b> <!-- 评论者 -->
                                于{{ message.published_time }}留言
                            </div>
                        </header>
                        <div class="am-comment-bd"
                             style="background-color: white">{{ message.content|safe_markdown }}</div> <!-- 评论内容 -->
                    </div>
                </li>
            </ul>
        {% empty %}
        {% endfor %}

    </div>

    </body>
{% endblock %}
</html>

msb/templates/msb/msb_manage.html
{% extends 'blog_articles/newmanage/index.html' %}
{% block title %}
    留言管理
{% endblock %}
{% block content %}
    <div class="card-box">
        <div class="content">
            <div class="am-g am-g-fixed" style="min-height: 525px; height: 100%">

                <div class=" am-u-lg-12 am-u-md-12" style="padding-top: 25px">
                    <table class="am-table am-table-hover">
                        <thead>
                        <tr>
                            <th>内容</th>
                            <th>名称</th>
                            <th>邮箱</th>
                            <th>时间</th>
                            <th>操作</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for message in message_list %}
                            <tr>
                                <td>{{ message.content| truncatechars:25 }}</td>
                                <td>{{ message.author_name }}</td>
                                <td>{{ message.email }}</td>
                                <td>{{ message.published_time }}</td>
                                <td>
                                    <a href="{% url 'msb:delete' message.id %}">
                                        <button class="am-btn am-btn-warning am-btn-xs">
                                            <span class="am-icon-trash-o"></span> 删除
                                        </button>
                                    </a>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
{% endblock %}